import { Router } from 'express';
import crypto from 'crypto';
import PDFDocument from 'pdfkit';
import { logger } from '../lib/logger.js';
import { asyncRoute } from '../middleware/errorHandler.js';

export const exportRouter = Router();

/**
 * POST /api/export/evidence
 * Accepts a JSON payload containing trace data.
 * Generates a SHA-256 hash of the JSON and produces a BSA Section 63 Compliant Evidence PDF.
 */
exportRouter.post(
  '/export/evidence',
  asyncRoute(async (req, res) => {
    const traceData = req.body;
    
    if (!traceData || Object.keys(traceData).length === 0) {
      return res.status(400).json({ ok: false, message: 'Missing trace data payload' });
    }

    // 1. Generate SHA-256 hash of the payload
    const jsonString = JSON.stringify(traceData);
    const hash = crypto.createHash('sha256').update(jsonString).digest('hex');
    const timestamp = new Date().toISOString();

    logger.info('Generating Evidence Export PDF', { hash });

    // 2. Setup PDF document
    const doc = new PDFDocument({ margin: 50 });
    
    // 3. Pipe to response
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="CryptoTrace_Evidence_${Date.now()}.pdf"`);
    doc.pipe(res);

    // Document Header
    doc
      .fontSize(20)
      .font('Helvetica-Bold')
      .text('CRYPTOTRACE SYSTEM', { align: 'center' })
      .moveDown(0.5);

    doc
      .fontSize(14)
      .text('BSA Section 63 Compliant Evidence Export', { align: 'center' })
      .moveDown(2);

    // --- SCHEDULE PART A: Metadata & Integrity ---
    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('SCHEDULE PART A: Metadata & Integrity')
      .moveDown(0.5);
      
    doc
      .fontSize(10)
      .font('Helvetica')
      .text(`Generated At (UTC): ${timestamp}`)
      .moveDown(0.5)
      .text(`Trace Payload SHA-256 Checksum:`)
      .font('Courier')
      .text(hash)
      .moveDown(2);

    // --- SCHEDULE PART B: Trace Summary ---
    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('SCHEDULE PART B: Trace Summary')
      .moveDown(0.5);

    doc
      .fontSize(10)
      .font('Helvetica');

    if (traceData.targetAddress) {
      doc.text(`Target Wallet: ${traceData.targetAddress}`).moveDown(0.5);
    }

    if (traceData.stats) {
      const stats = traceData.stats;
      doc
        .text(`Total Nodes Traced: ${stats.nodesScanned || 0}`)
        .text(`Total Hops (Depth): ${stats.maxDepth || 0}`)
        .text(`Exchanges Identified: ${stats.exchangeCashouts || 0}`)
        .moveDown(1);
    }

    if (traceData.warnings && traceData.warnings.length > 0) {
      doc
        .font('Helvetica-Bold')
        .text('Critical Alerts / Warnings:')
        .font('Helvetica')
        .moveDown(0.5);
        
      traceData.warnings.forEach(w => {
        doc.text(`- [${w.severity || 'WARN'}] ${w.message}`);
      });
      doc.moveDown(1);
    }

    // Add a disclaimer at the bottom
    doc
      .moveDown(2)
      .fontSize(8)
      .font('Helvetica-Oblique')
      .text(
        'CONFIDENTIALITY NOTICE: This document contains sensitive law enforcement intelligence ' +
        'generated by the CryptoTrace system. It is intended solely for authorized personnel.',
        { align: 'justify' }
      );

    // Finalize PDF
    doc.end();
  })
);
